/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BDS_MCJAVAAPI_TickFunc */

#ifndef _Included_BDS_MCJAVAAPI_TickFunc
#define _Included_BDS_MCJAVAAPI_TickFunc
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
