/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BDS_MCJAVAAPI */

#ifndef _Included_BDS_MCJAVAAPI
#define _Included_BDS_MCJAVAAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BDS_MCJAVAAPI
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BDS_MCJAVAAPI_log
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    addBeforeActListener
 * Signature: (Ljava/lang/String;LBDS/MCJAVAAPI/EventCab;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_addBeforeActListener
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    addAfterActListener
 * Signature: (Ljava/lang/String;LBDS/MCJAVAAPI/EventCab;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_addAfterActListener
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    removeBeforeActListener
 * Signature: (Ljava/lang/String;LBDS/MCJAVAAPI/EventCab;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_removeBeforeActListener
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    removeAfterActListener
 * Signature: (Ljava/lang/String;LBDS/MCJAVAAPI/EventCab;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_removeAfterActListener
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    postTick
 * Signature: (LBDS/MCJAVAAPI/TickFunc;)V
 */
JNIEXPORT void JNICALL Java_BDS_MCJAVAAPI_postTick
  (JNIEnv *, jobject, jobject);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    setCommandDescribe
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BDS_MCJAVAAPI_setCommandDescribe
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    runcmd
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_runcmd
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    logout
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BDS_MCJAVAAPI_logout
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    getOnLinePlayers
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BDS_MCJAVAAPI_getOnLinePlayers
  (JNIEnv *, jobject);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    JSErunScript
 * Signature: (Ljava/lang/String;LBDS/MCJAVAAPI/JSECab;)V
 */
JNIEXPORT void JNICALL Java_BDS_MCJAVAAPI_JSErunScript
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    JSEfireCustomEvent
 * Signature: (Ljava/lang/String;Ljava/lang/String;LBDS/MCJAVAAPI/JSECab;)V
 */
JNIEXPORT void JNICALL Java_BDS_MCJAVAAPI_JSEfireCustomEvent
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    reNameByUuid
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_reNameByUuid
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    addPlayerItem
 * Signature: (Ljava/lang/String;ISB)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_addPlayerItem
  (JNIEnv *, jobject, jstring, jint, jshort, jbyte);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    selectPlayer
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BDS_MCJAVAAPI_selectPlayer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    talkAs
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_talkAs
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    runcmdAs
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_runcmdAs
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    disconnectClient
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_disconnectClient
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    sendText
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_sendText
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    sendSimpleForm
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BDS_MCJAVAAPI_sendSimpleForm
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    sendModalForm
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BDS_MCJAVAAPI_sendModalForm
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    sendCustomForm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BDS_MCJAVAAPI_sendCustomForm
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    releaseForm
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_releaseForm
  (JNIEnv *, jobject, jint);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    getscoreboard
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BDS_MCJAVAAPI_getscoreboard
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    setscoreboard
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_setscoreboard
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    setServerMotd
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_setServerMotd
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    getscoreById
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BDS_MCJAVAAPI_getscoreById
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    setscoreById
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_BDS_MCJAVAAPI_setscoreById
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    dlsym
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_BDS_MCJAVAAPI_dlsym
  (JNIEnv *, jobject, jint);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    readHardMemory
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_BDS_MCJAVAAPI_readHardMemory
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     BDS_MCJAVAAPI
 * Method:    writeHardMemory
 * Signature: (I[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_BDS_MCJAVAAPI_writeHardMemory
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
